### PR TITLE
showing auto-merge feature

### PR DESCRIPTION
**Pull request by thst-nordic**

### CODE REVIEW

**Review by tejlmand — APPROVED** [review]
Approved, but @thst-nordic  you should still add `signed-off-by` even when it's a revert commit.

**Comment by thst-nordic** [comment]
fixed signed-by.  

I will enable auto-rebase-merge. 
image

**Comment by tejlmand** [comment]
> I will enable auto-rebase-merge.

@thst-nordic Is this something we plan to do generally in our repositories ?
asking since you seem to be playing with this feature.

**Comment by thst-nordic** [comment]
Discussion is here:  https://projecttools.nordicsemi.no/jira/browse/NCSDK-12897

summary is no.

**Pull request merged**
